### ISSUE TITLE
0.10.0 release

### ISSUE THREAD

**Issue by alexcarol** [cookielab/terraform-kubernetes-cluster-autoscaler-aws#7]
Would it be possible to create a new release with the current changes in master?

Thanks!

**Comment by Vrtak-CZ** [comment]
i will do new release soon when i get time to finish merging / closing all remaining PRs. Stay tuned!

**Comment by Vrtak-CZ** [comment]
0.10.0 released

**Comment by alexcarol** [comment]
Thanks!
