### ISSUE TITLE
Disappeared code

### ISSUE THREAD

**Issue by alexcarol** [cookielab/terraform-kubernetes-cluster-autoscaler-aws#8]
Hi, I got two pull requests merged recently, that are nowhere to be seen in master:
- https://github.com/cookielab/terraform-kubernetes-cluster-autoscaler-aws/pull/5 
- https://github.com/cookielab/terraform-kubernetes-cluster-autoscaler-aws/pull/6

I'm assuming it was not intended, is everything ok with that?

Thanks!

**Comment by Vrtak-CZ** [comment]
Thanks for pinging us! I was not intended at all. It was huge mistake on our side when this repo in github is mirror of original repo in our gitlab (we are switching this repo to be primary one soon). So PRs were merged here on github and not synced back to our gitlab. I was able to restore #5 but #6 was applied by another commit from another PR so it's lost 😞 

I'm so sorry this should never happen!
